services:
  dload-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dload-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseSerialGC -XX:+UseContainerSupport -XX:TieredStopAtLevel=1 -Xss256k"
    volumes:
      - /data/media:/downloads
    restart: unless-stopped
    network_mode: "container:surfshark-vpn"

  dload-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dload-frontend
    restart: unless-stopped
    depends_on:
      - dload-backend
    networks:
      - surfshark_vpn_network
      - nginx_reverse_proxy_network

networks:
  surfshark_vpn_network:
    external: true
  nginx_reverse_proxy_network:
    external: true
