services:
  dload-vpn:
    build:
      context: ./vpn
      dockerfile: Dockerfile
    container_name: dload-vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /lib/modules:/lib/modules:ro
    restart: unless-stopped
    networks:
      - downloader-network

  dload-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dload-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseSerialGC -XX:+UseContainerSupport -XX:TieredStopAtLevel=1 -Xss256k"
    volumes:
      - /data/media:/downloads
    restart: unless-stopped
    depends_on:
      - dload-vpn
    network_mode: "service:dload-vpn"

  dload-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dload-frontend
    restart: unless-stopped
    depends_on:
      - dload-backend
    networks:
      - downloader-network
      - nginx_reverse_proxy_network

networks:
  downloader-network:
    driver: bridge
  nginx_reverse_proxy_network:
    external: true
